name: Ten
version: '1.0'
main: dev.addition.ten.Ten
api-version: '1.21'
authors: [ 3add ]
description: The RandomKits experience by 3add
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
    FastAsyncWorldEdit:
      load: BEFORE
      required: false
      join-classpath: true